### PR TITLE
Ux improvements

### PR DESCRIPTION
**Pull request by kopyl**

### CODE REVIEW

**Comment by strint** [comment]
@kopyl  Thanks a lot!

We find that it's useful to add graph file and device when run compile, and we have added it: https://github.com/siliconflow/onediff/blob/cf5e835b41b552bcbbf4673b5859861f8a7c09c9/onediff_comfy_nodes/_nodes.py#L631

**Comment by kopyl** [comment]
@strint thank you. How do you now do it [here](https://github.com/siliconflow/onediff/blob/main/examples/text_to_image.py)?

**Comment by strint** [comment]
> onediff/onediff_comfy_nodes/_nodes.py

Here is the example:
```
oneflow_compile(model,
                use_graph=True,
                options={
                    "graph_file": file_path,
                    "graph_file_device": device,
                },
            )
```

**Comment by kopyl** [comment]
@strint this is amazing, thank you very much.

I just added a notebook, please merge it: https://github.com/siliconflow/onediff/pull/475

**Pull request closed without merging**
