### PR TITLE
add ability to save and load compiled pipelines

### PR DESCRIPTION
**Pull request by isidentical**
we use the following `save_pipe`/`load_pipe` logic in production so maybe it is worth adding to upstream

### CODE REVIEW

**Comment by isidentical** [comment]
@strint what do you think?

**Comment by strint** [comment]
> @strint what do you think?

This is just what we need.

We will add a Contributor License Agreement (CLA), and then start to review this.

**Comment by strint** [comment]
> > @strint what do you think?
> 
> This is just what we need.
> 
> We will add a Contributor License Agreement (CLA), and then start to review this.

We will ignore CLA to make it simple.

**Comment by isidentical** [comment]
Closing this since #677 already adds the constructs.

**Pull request closed without merging**
